name: Deploy to Heroku.

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

    steps:
    - name: Print environment variables for debugging
      run: |
        echo "DOCKER_HUB_USERNAME=${DOCKER_HUB_USERNAME}"
        echo "HEROKU_APP_NAME=${HEROKU_APP_NAME}"

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push to Docker Hub (and load for tagging)
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64
        push: true
        load: true  # <- This makes the image available locally for tagging
        tags: |
          andrewbarwise/app:latest
          andrewbarwise/app:1.0.0


    - name: Install Heroku CLI
      run: |
        wget https://cli-assets.heroku.com/install-ubuntu.sh
        chmod +x install-ubuntu.sh
        ./install-ubuntu.sh

    - name: Log in to Heroku Container Registry
      run: docker login --username=_ --password-stdin registry.heroku.com <<< "$HEROKU_API_KEY"

    - name: Tag Docker image for Heroku
      run: docker tag andrewbarwise/app:latest registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

    - name: Push Docker image to Heroku Registry
      run: docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

    - name: Release Docker image to Heroku
      run: heroku container:release web --app $HEROKU_APP_NAME