name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

    steps:
    - name: Print environment variables for debugging
      run: |
        echo "DOCKER_HUB_USERNAME=${DOCKER_HUB_USERNAME}"
        echo "HEROKU_APP_NAME=${HEROKU_APP_NAME}"

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          user/app:latest
          user/app:1.0.0

    - name: Deploy to Heroku
      run: |
        echo "Deploying to Heroku..."
        docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:latest
        echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com
        docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:latest registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
        docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
        heroku container:release web --app $HEROKU_APP_NAME

        